name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "qrcode_hub"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "ffe32c8b-6365-4d68-ac2c-52f7de9141c2"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qrcode_hub_dev"
database_id = "ffe32c8b-6365-4d68-ac2c-52f7de9141c2"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
